### PR TITLE
Add spamming as an example of unacceptable behaviour

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Based on some recent activity in the Dask Slack I'd like to add posting spam as an example of unacceptable behaviour to our code of conduct. Open to wording improvements 😊.

Also as a Dask Owner I've added myself to the CoC committee (@mrocklin, @jrbourbeau could you add me to the mailing list?).

cc @fjetter, @quasiben

### CODE REVIEW

**Comment by mrocklin** [comment]
I've had difficulty finding that group actually.  Since making this doc we've gotten control over the dask.org email namespace.  I'm inclined to make a new group like `conduct@dask.org` or `report@dask.org` and manage it there.  Any objections?  Any recommendations on a name?  

@jacobtomlinson I'm also happy to, instead of making the group, work to make sure that you have sufficient permissions to make such a group and then hand this task over to you.  Any interest?

**Review by mrocklin — APPROVED** [review]

**Comment by jacobtomlinson** [comment]
> I'm also happy to, instead of making the group, work to make sure that you have sufficient permissions to make such a group and then hand this task over to you. Any interest?

Sounds good to me. I like `conduct@dask.org`.

**Review by fjetter — APPROVED** [review]

**Comment by jacobtomlinson** [comment]
With two approvals I'm going to merge this.

**Review by jrbourbeau — COMMENTED** [review]
Thanks @jacobtomlinson

**Pull request merged**
